### ISSUE TITLE
Can you please fix the first example?

### ISSUE THREAD

**Issue by EmTee70** [intrica/elasticsearch-d#5]
```// Basic query


Parameters searchParams;
searchParams["body"] = "<elasticsearch query>";
searchParams["index"] = "es_test_index";

auto response = client.search(params);
puts response.jsonBody;
```

`Parameters searchParams;` must be 
`ESParams searchParams;`

and the `client.search(params);`

must than be:
`client.search(searchParams);`

But unfortunately I only get errors when tying to do a query:
Can you give an example which corresponds to an query here:

http://joelabrahamsson.com/elasticsearch-101/

My error is this:
Elasticsearch request failed (GET notices/_search): {"error":"SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[o8EIlU3ZTtSbWccPbdVbYw][notices][0]: SearchParseException[[notices][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]]; nested: ElasticSearchParseException[Failed to derive xcontent from (offset=0, length=21): [60, 101, 108, 97, 115, 116, 105, 99, 115, 101, 97, 114, 99, 104, 32, 113, 117, 101, 114, 121, 62]]; }{[o8EIlU3ZTtSbWccPbdVbYw][notices][1]: SearchParseException[[notices][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]]; nested: ElasticSearchParseException[Failed to derive xcontent from (offset=0, length=21): [60, 101, 108, 97, 115, 116, 105, 99, 115, 101, 97, 114, 99, 104, 32, 113, 117, 101, 114, 121, 62]]; }]","status":500}

When tying with:
  ESParams searchParams;
  searchParams["body"] = "<elasticsearch query>";
  searchParams["index"] = "notices";  //  stored notices
  searchParams["title"] = "vestas";     // should search for all titles including name 'vestas'
  auto response = client.search(searchParams);

Any hint?

**Comment by dmonagle** [comment]
Hi mate. I've updated the example and fixed formatting in the README. 

I can't really help you with that error unfortunately. My advice would always be to see if you request works with a CURL request. I'm not sure that setting the body to an empty string is the right thing to do however. If you don't want a body, you shouldn't set it at all.
